namespace GlobalEnums
{
	public enum MainMenuState
	{
		LOGO = 0,
		MAIN_MENU = 1,
		OPTIONS_MENU = 2,
		GAMEPAD_MENU = 3,
		KEYBOARD_MENU = 4,
		SAVE_PROFILES = 5,
		AUDIO_MENU = 6,
		VIDEO_MENU = 7,
		EXIT_PROMPT = 8,
		OVERSCAN_MENU = 9,
		GAME_OPTIONS_MENU = 10,
		ACHIEVEMENTS_MENU = 11,
		QUIT_GAME_PROMPT = 12,
		RESOLUTION_PROMPT = 13,
		BRIGHTNESS_MENU = 14,
		PAUSE_MENU = 15,
		PLAY_MODE_MENU = 16,
		EXTRAS_MENU = 17,
		REMAP_GAMEPAD_MENU = 18,
		EXTRAS_CONTENT_MENU = 19,
		ENGAGE_MENU = 20,
		NO_SAVE_MENU = 21,
	}
}
