namespace HutongGames.PlayMaker
{
	public enum ParamDataType
	{
		Integer = 0,
		Boolean = 1,
		Float = 2,
		String = 3,
		Color = 4,
		ObjectReference = 5,
		LayerMask = 6,
		Enum = 7,
		Vector2 = 8,
		Vector3 = 9,
		Vector4 = 10,
		Rect = 11,
		Array = 12,
		Character = 13,
		AnimationCurve = 14,
		FsmFloat = 15,
		FsmInt = 16,
		FsmBool = 17,
		FsmString = 18,
		FsmGameObject = 19,
		FsmOwnerDefault = 20,
		FunctionCall = 21,
		FsmAnimationCurve = 22,
		FsmEvent = 23,
		FsmObject = 24,
		FsmColor = 25,
		Unsupported = 26,
		GameObject = 27,
		FsmVector3 = 28,
		LayoutOption = 29,
		FsmRect = 30,
		FsmEventTarget = 31,
		FsmMaterial = 32,
		FsmTexture = 33,
		Quaternion = 34,
		FsmQuaternion = 35,
		FsmProperty = 36,
		FsmVector2 = 37,
		FsmTemplateControl = 38,
		FsmVar = 39,
		CustomClass = 40,
		FsmArray = 41,
		FsmEnum = 42,
	}
}
