using UnityEngine;
using InControl;
using GlobalEnums;
using UnityEngine.EventSystems;
using UnityEngine.UI;
using UnityEngine.Audio;

public class UIManager : MonoBehaviour
{
	public MenuAudioController uiAudioPlayer;
	public HollowKnightInputModule inputModule;
	public float MENU_FADE_SPEED;
	public UIState uiState;
	public MainMenuState menuState;
	public EventSystem eventSystem;
	public Canvas UICanvas;
	public CanvasGroup modalDimmer;
	public CanvasScaler canvasScaler;
	public AudioMixerSnapshot gameplaySnapshot;
	public AudioMixerSnapshot menuSilenceSnapshot;
	public AudioMixerSnapshot menuPauseSnapshot;
	public CanvasGroup mainMenuScreen;
	public MainMenuOptions mainMenuButtons;
	public SpriteRenderer gameTitle;
	public PlayMakerFSM subtitleFSM;
	public CanvasGroup saveProfileScreen;
	public CanvasGroup saveProfileTitle;
	public CanvasGroup saveProfileControls;
	public Animator saveProfileTopFleur;
	public PreselectOption saveSlots;
	public SaveSlotButton slotOne;
	public SaveSlotButton slotTwo;
	public SaveSlotButton slotThree;
	public SaveSlotButton slotFour;
	public CheckpointSprite checkpointSprite;
	public MenuScreen optionsMenuScreen;
	public MenuScreen gameOptionsMenuScreen;
	public GameMenuOptions gameMenuOptions;
	public MenuLanguageSetting languageSetting;
	public MenuSetting backerCreditsSetting;
	public MenuSetting nativeAchievementsSetting;
	public MenuSetting nativeInputSetting;
	public MenuSetting controllerRumbleSetting;
	public MenuScreen audioMenuScreen;
	public MenuAudioSlider masterSlider;
	public MenuAudioSlider musicSlider;
	public MenuAudioSlider soundSlider;
	public MenuScreen videoMenuScreen;
	public VideoMenuOptions videoMenuOptions;
	public MenuResolutionSetting resolutionOption;
	public ResolutionCountdownTimer countdownTimer;
	public MenuSetting fullscreenOption;
	public MenuSetting vsyncOption;
	public MenuSetting particlesOption;
	public MenuSetting shadersOption;
	public MenuDisplaySetting displayOption;
	public MenuSetting frameCapOption;
	public MenuScreen gamepadMenuScreen;
	public ControllerDetect controllerDetect;
	public MenuScreen remapGamepadMenuScreen;
	public MenuScreen keyboardMenuScreen;
	public MenuScreen overscanMenuScreen;
	public OverscanSetting overscanSetting;
	public MenuScreen brightnessMenuScreen;
	public BrightnessSetting brightnessSetting;
	public MenuScreen achievementsMenuScreen;
	public RectTransform achievementListRect;
	public MenuAchievementsList menuAchievementsList;
	public Sprite hiddenIcon;
	public GameObject achievementsPopupPanel;
	public MenuScreen extrasMenuScreen;
	public MenuScreen extrasContentMenuScreen;
	public MenuScreen playModeMenuScreen;
	public Animator pauseMenuAnimator;
	public MenuScreen pauseMenuScreen;
	public MenuScreen engageMenuScreen;
	public bool didLeaveEngageMenu;
	public MenuScreen noSaveMenuScreen;
	public MenuScreen quitGamePrompt;
	public MenuScreen returnMainMenuPrompt;
	public MenuScreen resolutionPrompt;
	[SerializeField]
	private CinematicSkipPopup cinematicSkipPopup;
	public UIButtonSkins uiButtonSkins;
}
